style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/shakir85/Terraform-Modules
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - enh
        - refactor
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      enh: Ehancements
      refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
