name: PR Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - feat/tools-pipeline

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify repo contents
        run: pwd; ls -l

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
          curl \
          wget \
          unzip \
          gnupg \
          software-properties-common \
          git \
          && rm -rf /var/lib/apt/lists/*
      
      - name: Install tflint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      
      - name: Test
        run: tflint --version