name: PR Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - feat/tools-pipeline

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify repo contents
        run: pwd; ls -l

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
          curl \
          wget \
          unzip \
          gnupg \
          software-properties-common \
          git \
          && rm -rf /var/lib/apt/lists/*
      
      - name: Install tflint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      
      - name: Install Terraform
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list && \
          apt-get update && apt-get install terraform

      - name: Check tflint version
        run: tflint --version
      
      - name: TF Formatting
        run: terraform fmt -recursive

      # - name: Lint TF modules
      #   run: tflint --recursive
