name: PR Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  code-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/shakir85/tf-tools:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: TF Formatting
        run: terraform fmt -recursive

      - name: Lint TF modules
        run: tflint --recursive

      # - name: Generate VM Module Docs
      #   run: terraform-docs markdown table --output-file README.md --output-mode inject ./proxmox/vm

      # - name: Generate LX Module Docs
      #   run: terraform-docs markdown table --output-file README.md --output-mode inject ./proxmox/lxc

      # - name: Generate Cloud-Image Module Docs
      #   run: terraform-docs markdown table --output-file README.md --output-mode inject ./proxmox/get-cloud-image
