name: PR Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: foo  # Replace 'foo' with the actual image name

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify repo contents
        run: ls -la /github/workspace

      - name: Run tests
        run: echo "Run your tests here!"