name: PR Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  code-lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
          curl \
          wget \
          unzip \
          gnupg \
          software-properties-common \
          git \
          && rm -rf /var/lib/apt/lists/*
      
      - name: Install tflint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      
      - name: Install Terraform
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list && \
          apt-get update && apt-get install terraform
      
      - name: Install Terraform Docs
        run: |
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs /usr/local/bin/terraform-docs

      - name: TF Formatting
        run: terraform fmt -recursive

      - name: Lint TF modules
        run: tflint --recursive

      - name: Generate VM Module Docs
        run: terraform-docs markdown table --output-file README.md --output-mode inject ./proxmox/vm

      - name: Generate LX Module Docs
        run: terraform-docs markdown table --output-file README.md --output-mode inject ./proxmox/lxc

      - name: Generate Cloud-Image Module Docs
        run: terraform-docs markdown table --output-file README.md --output-mode inject ./proxmox/get-cloud-image
